load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "//projects/ghidra/tutorial/docs",
    ],
    data = [
        "//projects/ghidra/tutorial/data",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
