load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "analysis",
    srcs = [
        "//projects/networking/docs/analysis/tools",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
