load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "docs",
    srcs = [
        "//projects/networking/gopher/docs",
        "//projects/networking/mqtt/docs",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
