load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "system",
    srcs = [
        "user.md",
        "packages.md",
        "services.md",
        "scheduling.md",
    ],
    index = "index.md",
    visibility = ["//visibility:public"],
)
