load("//rules:doc.bzl", "doc_section")

doc_section(
    name = "tools",
    srcs = [
        "tcpdump.md",
        "termshark.md",
        "tshark.md",
        "wireshark.md",
    ],
    index = "index.md",
    data = ["//projects/networking/docs/analysis/tools/data"],
    visibility = ["//visibility:public"],
)
